### ISSUE TITLE
Error compile with ImageMagick 7.1 CentOS Stream 10

### ISSUE THREAD

**Issue by masarinetwork** [cubicdaiya/ngx_small_light#104]
-o objs/addon/src/ngx_http_small_light_type.o \
        ../ngx_small_light/src/ngx_http_small_light_type.c
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I/usr/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_CHANNEL_MASK_DEPTH=32  -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-6 -pthread -I/usr/include/libxml2 -DWITH_GZFILEOP -I/usr/include/webp -DNGX_HTTP_SMALL_LIGHT_IMLIB2_ENABLED -DNGX_HTTP_SMALL_LIGHT_GD_ENABLED  -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I objs -I src/http -I src/http/modules \
        -o objs/addon/src/ngx_http_small_light_imagemagick.o \
        ../ngx_small_light/src/ngx_http_small_light_imagemagick.c
../ngx_small_light/src/ngx_http_small_light_imagemagick.c: In function ‘ngx_http_small_light_imagemagick_process’:
../ngx_small_light/src/ngx_http_small_light_imagemagick.c:236:22: error: implicit declaration of function ‘MagickTransformImage’; did you mean ‘MagickTransposeImage’? [-Wimplicit-function-declaration]
  236 |         trans_wand = MagickTransformImage(ictx->wand, (char *)crop_geo, (char *)size_geo);
      |                      ^~~~~~~~~~~~~~~~~~~~
      |                      MagickTransposeImage
../ngx_small_light/src/ngx_http_small_light_imagemagick.c:236:20: error: assignment to ‘MagickWand *’ {aka ‘struct _MagickWand *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  236 |         trans_wand = MagickTransformImage(ictx->wand, (char *)crop_geo, (char *)size_geo);
      |                    ^
../ngx_small_light/src/ngx_http_small_light_imagemagick.c:281:18: error: too few arguments to function ‘MagickCompositeImage’
  281 |         status = MagickCompositeImage(canvas_wand, ictx->wand, AtopCompositeOp, sz.dx, sz.dy);
      |                  ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/ImageMagick-7/wand/MagickWand.h:91,
                 from ../ngx_small_light/src/ngx_http_small_light_imagemagick.h:26,
                 from ../ngx_small_light/src/ngx_http_small_light_imagemagick.c:24:
/usr/include/ImageMagick-7/MagickWand/magick-image.h:123:3: note: declared here
  123 |   MagickCompositeImage(MagickWand *,const MagickWand *,const CompositeOperator,
      |   ^~~~~~~~~~~~~~~~~~~~
../ngx_small_light/src/ngx_http_small_light_imagemagick.c:461:9: error: implicit declaration of function ‘MagickCompositeImageChannel’; did you mean ‘MagickCompositeImageGravity’? [-Wimplicit-function-declaration]
  461 |         MagickCompositeImageChannel(ictx->wand, AllChannels, icon_wand, OverCompositeOp, sz.ix, sz.iy);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         MagickCompositeImageGravity
make[1]: *** [objs/Makefile:1284: objs/addon/src/ngx_http_small_light_imagemagick.o] Error 1
make[1]: Leaving directory '/usr/src/nginx-1.29.1'
make: *** [Makefile:16: modules] Error 2
[root@www nginx-1.29.1]# magick --version
Version: ImageMagick 7.1.1-47 Q16-HDRI x86_64 22763 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib zstd
Compiler: gcc (14.2)
